import { NextRequest } from 'next/server';
import { authenticateRequest, jsonError } from '@/lib/auth';
import { supabaseAdmin } from '@/lib/supabase';

/**
 * POST /api/tasks — Create a new task.
 * All receipts with this task_id will be grouped.
 * 
 * v1.1: Optionally accepts `key_hash` for E2E encrypted tasks.
 * The key_hash is SHA-256(viewing_key) — the server never sees the actual key.
 */
export async function POST(req: NextRequest) {
  const auth = await authenticateRequest(req);
  if (!auth) return jsonError('Invalid or missing API key', 401);

  let body: {
    agent_id: string;
    name: string;
    description?: string;
    key_hash?: string; // v1.1: SHA-256 of the AES-256-GCM viewing key
  };
  try {
    body = await req.json();
  } catch {
    return jsonError('Invalid JSON body', 400);
  }

  if (!body.agent_id || !body.name) {
    return jsonError('Missing required fields: agent_id, name', 400);
  }

  // v1.1: Validate key_hash format if provided (must be 64-char hex SHA-256)
  if (body.key_hash !== undefined && body.key_hash !== null) {
    if (!/^[a-f0-9]{64}$/.test(body.key_hash)) {
      return jsonError('key_hash must be a 64-character hex SHA-256 hash', 400);
    }
  }

  // Resolve agent UUID from agent_id string
  const { data: agent } = await supabaseAdmin
    .from('agents')
    .select('id')
    .eq('agent_id', body.agent_id)
    .eq('owner_id', auth.ownerId)
    .single();

  if (!agent) {
    return jsonError('Agent not found', 404);
  }

  // Create the task (slug auto-generated by DB trigger)
  const insertData: Record<string, unknown> = {
    agent_id: agent.id,
    owner_id: auth.ownerId,
    name: body.name,
    description: body.description || null,
    slug: '', // trigger will generate
  };

  // v1.1: Store key_hash if provided (E2E encrypted task)
  if (body.key_hash) {
    insertData.key_hash = body.key_hash;
  }

  const { data: task, error } = await supabaseAdmin
    .from('tasks')
    .insert(insertData)
    .select('id, slug, name, status, key_hash, created_at')
    .single();

  if (error) {
    console.error('Task creation error:', error);
    return jsonError('Failed to create task', 500);
  }

  const shareUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://openclawscan.xyz'}/task/${task.slug}`;

  return Response.json(
    {
      task_id: task.id,
      slug: task.slug,
      share_url: shareUrl,
      status: task.status,
      total_receipts: 0,
      total_duration_ms: 0,
      total_cost_usd: 0,
      key_hash: task.key_hash || null, // v1.1: null for v1.0 tasks
    },
    { status: 201 }
  );
}

/**
 * PATCH /api/tasks — Update task status.
 * Body: { task_id: string, status: 'completed' | 'failed', encrypted_summary?: string }
 * 
 * v1.1: Optionally accepts `encrypted_summary` — an AES-256-GCM encrypted
 * summary of the task results. Decrypted client-side with the viewing key.
 */
export async function PATCH(req: NextRequest) {
  const auth = await authenticateRequest(req);
  if (!auth) return jsonError('Invalid or missing API key', 401);

  let body: {
    task_id: string;
    status: string;
    encrypted_summary?: string; // v1.1: AES-256-GCM encrypted task summary
  };
  try {
    body = await req.json();
  } catch {
    return jsonError('Invalid JSON body', 400);
  }

  if (!body.task_id || !body.status) {
    return jsonError('Missing required fields: task_id, status', 400);
  }

  if (!['completed', 'failed'].includes(body.status)) {
    return jsonError('Status must be "completed" or "failed"', 400);
  }

  // v1.1: Validate encrypted_summary format if provided (must be valid base64)
  if (body.encrypted_summary) {
    try {
      const buf = Buffer.from(body.encrypted_summary, 'base64');
      if (buf.length < 28) {
        return jsonError('encrypted_summary blob too short — invalid AES-256-GCM format', 400);
      }
    } catch {
      return jsonError('encrypted_summary must be valid base64', 400);
    }
  }

  const updateData: Record<string, unknown> = {
    status: body.status,
  };

  if (body.status === 'completed') {
    updateData.completed_at = new Date().toISOString();
  }

  // v1.1: Store encrypted summary if provided
  if (body.encrypted_summary) {
    updateData.encrypted_summary = body.encrypted_summary;
  }

  const { data: task, error } = await supabaseAdmin
    .from('tasks')
    .update(updateData)
    .eq('id', body.task_id)
    .eq('owner_id', auth.ownerId)
    .select('id, slug, name, status, total_receipts, total_duration_ms, total_cost_usd, key_hash, completed_at')
    .single();

  if (error || !task) {
    return jsonError('Task not found or update failed', 404);
  }

  const shareUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://openclawscan.xyz'}/task/${task.slug}`;

  return Response.json({
    task_id: task.id,
    slug: task.slug,
    share_url: shareUrl,
    status: task.status,
    total_receipts: task.total_receipts,
    total_duration_ms: task.total_duration_ms,
    total_cost_usd: task.total_cost_usd,
    key_hash: task.key_hash || null, // v1.1
  });
}
