import { NextRequest } from 'next/server';
import { authenticateRequest, jsonError } from '@/lib/auth';
import { supabaseAdmin } from '@/lib/supabase';

/**
 * POST /api/tasks — Create a new task.
 * All receipts with this task_id will be grouped.
 */
export async function POST(req: NextRequest) {
  const auth = await authenticateRequest(req);
  if (!auth) return jsonError('Invalid or missing API key', 401);

  let body: { agent_id: string; name: string; description?: string };
  try {
    body = await req.json();
  } catch {
    return jsonError('Invalid JSON body', 400);
  }

  if (!body.agent_id || !body.name) {
    return jsonError('Missing required fields: agent_id, name', 400);
  }

  // Resolve agent UUID from agent_id string
  const { data: agent } = await supabaseAdmin
    .from('agents')
    .select('id')
    .eq('agent_id', body.agent_id)
    .eq('owner_id', auth.ownerId)
    .single();

  if (!agent) {
    return jsonError('Agent not found', 404);
  }

  // Create the task (slug auto-generated by DB trigger)
  const { data: task, error } = await supabaseAdmin
    .from('tasks')
    .insert({
      agent_id: agent.id,
      owner_id: auth.ownerId,
      name: body.name,
      description: body.description || null,
      slug: '', // trigger will generate
    })
    .select('id, slug, name, status, created_at')
    .single();

  if (error) {
    console.error('Task creation error:', error);
    return jsonError('Failed to create task', 500);
  }

  const shareUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://openclawscan.xyz'}/task/${task.slug}`;

  return Response.json(
    {
      task_id: task.id,
      slug: task.slug,
      share_url: shareUrl,
      status: task.status,
      total_receipts: 0,
      total_duration_ms: 0,
      total_cost_usd: 0,
    },
    { status: 201 }
  );
}

/**
 * PATCH /api/tasks — Update task status.
 * Body: { task_id: string, status: 'completed' | 'failed' }
 */
export async function PATCH(req: NextRequest) {
  const auth = await authenticateRequest(req);
  if (!auth) return jsonError('Invalid or missing API key', 401);

  let body: { task_id: string; status: string };
  try {
    body = await req.json();
  } catch {
    return jsonError('Invalid JSON body', 400);
  }

  if (!body.task_id || !body.status) {
    return jsonError('Missing required fields: task_id, status', 400);
  }

  if (!['completed', 'failed'].includes(body.status)) {
    return jsonError('Status must be "completed" or "failed"', 400);
  }

  const updateData: Record<string, unknown> = {
    status: body.status,
  };

  if (body.status === 'completed') {
    updateData.completed_at = new Date().toISOString();
  }

  const { data: task, error } = await supabaseAdmin
    .from('tasks')
    .update(updateData)
    .eq('id', body.task_id)
    .eq('owner_id', auth.ownerId)
    .select('id, slug, name, status, total_receipts, total_duration_ms, total_cost_usd, completed_at')
    .single();

  if (error || !task) {
    return jsonError('Task not found or update failed', 404);
  }

  const shareUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://openclawscan.xyz'}/task/${task.slug}`;

  return Response.json({
    task_id: task.id,
    slug: task.slug,
    share_url: shareUrl,
    status: task.status,
    total_receipts: task.total_receipts,
    total_duration_ms: task.total_duration_ms,
    total_cost_usd: task.total_cost_usd,
  });
}
